"""empty message

Revision ID: 329b908c1637
Revises: cd8efaf8cdfe
Create Date: 2019-10-23 11:37:46.004788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329b908c1637'
down_revision = 'cd8efaf8cdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cities')
    op.drop_table('city_venue_address_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_venue_address_link',
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_address_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='city_venue_address_link_city_id_fkey'),
    sa.ForeignKeyConstraint(['venue_address_id'], ['venue_address.id'], name='city_venue_address_link_venue_address_id_fkey'),
    sa.PrimaryKeyConstraint('city_id', 'venue_address_id', name='city_venue_address_link_pkey')
    )
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name='cities_state_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cities_pkey')
    )
    op.drop_table('city')
    # ### end Alembic commands ###
