"""empty message

Revision ID: 463f939730b0
Revises: aeb0000a2c30
Create Date: 2019-10-04 15:34:44.535584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463f939730b0'
down_revision = 'aeb0000a2c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cities_venue_address_id_fkey', 'cities', type_='foreignkey')
    op.drop_column('cities', 'venue_address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('venue_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cities_venue_address_id_fkey', 'cities', 'venue_address', ['venue_address_id'], ['id'])
    # ### end Alembic commands ###
