"""empty message

Revision ID: 62cf8dacabb2
Revises: 463f939730b0
Create Date: 2019-10-04 15:41:13.649907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cf8dacabb2'
down_revision = '463f939730b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name', sa.String(length=120), nullable=True))
    op.drop_column('cities', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('cities', 'name')
    # ### end Alembic commands ###
