"""empty message

Revision ID: 939b6a510b75
Revises: 81faf743a87e
Create Date: 2019-10-04 13:59:12.642538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939b6a510b75'
down_revision = '81faf743a87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    # ### end Alembic commands ###
