"""empty message

Revision ID: cd8efaf8cdfe
Revises: 98993fcf2a2d
Create Date: 2019-10-21 15:16:19.843863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8efaf8cdfe'
down_revision = '98993fcf2a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cities', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cities', 'states', ['state_id'], ['id'])
    op.drop_column('cities', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_column('cities', 'state_id')
    op.drop_table('states')
    # ### end Alembic commands ###
